### ISSUE TITLE
Crash on start up

### ISSUE THREAD

**Issue by cofffeeelinux** [Um-Mitternacht/Bewitchment#213]
### Expected Behavior
Start

### Actual Behavior
Crashes when loading

### Steps to Reproduce
None

### Logs, in the event of a crash
https://paste.dimdev.org/awohacepof.mccrash

**Comment by Sunconure11** [comment]
Oh boy, I thought I fixed this. Use the latest build of forge.

**Comment by cofffeeelinux** [comment]
ok great thanks ill try it out and report back.

**Comment by cofffeeelinux** [comment]
Still having issues but i will continue to troubleshoot on my own, ill reopen another ticket if i cant get it going. Thanks for your help, love the hard work you do!
