### ISSUE TITLE
Grimore Gaia Book Crashing Server

### ISSUE THREAD

**Issue by Vahlmira** [Um-Mitternacht/Bewitchment#404]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  wings (wings-1.1.5-1.12.2.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
Contact their authors BEFORE contacting forge

// Quite honestly, I wouldn't worry myself about that.

Time: 8/12/19 3:26 PM
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at com.bewitchment.api.capability.magicpower.MagicPower.transfer(MagicPower.java:107)
	at com.bewitchment.common.block.tile.entity.TileEntityWitchesAltar.func_73660_a(TileEntityWitchesAltar.java:97)
	at net.minecraft.world.World.func_72939_s(World.java:1835)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.bewitchment.api.capability.magicpower.MagicPower.transfer(MagicPower.java:107)
	at com.bewitchment.common.block.tile.entity.TileEntityWitchesAltar.func_73660_a(TileEntityWitchesAltar.java:97)

-- Block entity being ticked --
Details:
	Name: bewitchment:stone_witches_altar // com.bewitchment.common.block.tile.entity.TileEntityWitchesAltar
	Block type: ID #610 (tile.bewitchment.stone_witches_altar // com.bewitchment.common.block.BlockWitchesAltar // bewitchment:stone_witches_altar)
	Block data value: 2 / 0x2 / 0b0010
	Block location: World: (-1162,66,-1745), Chunk: (at 6,4,15 in -73,-110; contains blocks -1168,0,-1760 to -1153,255,-1745), Region: (-3,-4; contains chunks -96,-128 to -65,-97, blocks -1536,0,-2048 to -1025,255,-1537)
	Actual block type: ID #610 (tile.bewitchment.stone_witches_altar // com.bewitchment.common.block.BlockWitchesAltar // bewitchment:stone_witches_altar)
	Actual block data value: 2 / 0x2 / 0b0010
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1835)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: Please Work
	All players: 2 total; [EntityPlayerMP['Vahlmira'/4701, l='Please Work', x=-501.71, y=63.00, z=2411.82], EntityPlayerMP['CupOfDrama'/6466, l='Please Work', x=-1152.51, y=66.00, z=-1751.78]]
	Chunk stats: ServerChunkCache: 1138 Drop: 0
	Level seed: 8379400885324874809
	Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: true
	Level generator options: {"landScheme":"continents","tempScheme":"medium_zones","rainScheme":"medium_zones","biomeSize":"medium","amplitude":1.1464789,"generateBopOre":true,"generatePoisonIvy":false,"generateBerryBushes":true,"generateThorns":true,"generateQuicksand":true,"generateLiquidPoison":true,"generateHotSprings":true,"generateNetherHives":true,"generateEndFeatures":true,"mainNoiseScaleX":80.0,"mainNoiseScaleY":160.0,"mainNoiseScaleZ":80.0,"coordinateScale":684.412,"heightScale":684.412,"upperLimitScale":512.0,"lowerLimitScale":512.0}
	Level spawn location: World: (575,70,107), Chunk: (at 15,4,11 in 35,6; contains blocks 560,0,96 to 575,255,111), Region: (1,0; contains chunks 32,0 to 63,31, blocks 512,0,0 to 1023,255,511)
	Level time: 8277400 game time, 4514 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 6000 (now: false), thunder time: 6000 (now: true)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (amd64) version 3.10.0-957.1.3.el7.x86_64
	Java Version: 1.8.0_201, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2880687760 bytes (2747 MB) / 4207411200 bytes (4012 MB) up to 4207411200 bytes (4012 MB)
	JVM Flags: 3 total; -Xmx4096M -Xms4096M -XX:MaxPermSize=256m
	IntCache: cache: 0, tcache: 3, allocated: 8, tallocated: 84
	FML: MCP 9.42 Powered by Forge 14.23.5.2838 41 mods loaded, 40 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                  | Version                | Source                                                | Signature                                |
	|:------ |:------------------- |:---------------------- |:----------------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft           | 1.12.2                 | minecraft.jar                                         | None                                     |
	| LCHIJA | mcp                 | 9.42                   | minecraft.jar                                         | None                                     |
	| LCHIJA | FML                 | 8.0.99.99              | forge1122.jar                                         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge               | 14.23.5.2838           | forge1122.jar                                         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | ageofweapons        | 0.13.5                 | Age+of+Weapons+1.12.2++(v.0.13.5).jar                 | None                                     |
	| LCHIJA | armourers_workshop  | 1.12.2-0.49.1          | Armourers-Workshop-1.12.2-0.49.1.jar                  | None                                     |
	| LCHIJA | astikorcarts        | 1.12.2-0.1.2.7         | astikorcarts-1.12.2-0.1.2.7.jar                       | None                                     |
	| LCHIJA | baubles             | 1.5.2                  | Baubles-1.12-1.5.2.jar                                | None                                     |
	| LCHIJA | patchouli           | 1.0-20                 | Patchouli-1.0-20.jar                                  | None                                     |
	| LCHIJA | bewitchment         | 0.20                   | bewitchment-1.12.2-0.0.20.jar                         | None                                     |
	| LCHIJA | bibliocraft         | 2.4.5                  | BiblioCraft[v2.4.5][MC1.12.2].jar                     | None                                     |
	| LCHIJA | biomesoplenty       | 7.0.1.2441             | BiomesOPlenty-1.12.2-7.0.1.2441-universal.jar         | None                                     |
	| LCHIJA | botania             | r1.10-361              | Botania+r1.10-361.jar                                 | None                                     |
	| LCHIJA | chameleon           | 1.12-4.1.3             | Chameleon-1.12-4.1.3.jar                              | None                                     |
	| LCHIJA | customspawner       | 3.11.4                 | Custom-Mob-Spawner-Mod-1.12.2.jar                     | None                                     |
	| LCHIJA | doggytalents        | 1.15.0.6               | DoggyTalents-1.12.2-1.15.0.6-universal.jar            | None                                     |
	| LCHIJA | mocreatures         | 12.0.5                 | DrZharks MoCreatures Mod-12.0.5.jar                   | None                                     |
	| LCHIJA | forbidden_arcanus   | 1.12.2-1.1.4           | forbidden_arcanus-1.12.2-1.1.4.jar                    | None                                     |
	| LCHIJA | llibrary            | 1.7.19                 | llibrary-1.7.19-1.12.2.jar                            | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LCHIJA | iceandfire          | 1.8.0                  | iceandfire-1.8.0.jar                                  | None                                     |
	| LCHIJA | ironchest           | 1.12.2-7.0.67.844      | ironchest-1.12.2-7.0.72.847.jar                       | None                                     |
	| LCHIJA | malisiscore         | 1.12.2-6.5.1-SNAPSHOT  | malisiscore-1.12.2-6.5.1.jar                          | None                                     |
	| LCHIJA | malisisdoors        | 1.12.2-7.3.0           | malisisdoors-1.12.2-7.3.0.jar                         | None                                     |
	| LCHIJA | radixcore           | 1.12.x-2.2.1           | RadixCore-1.12.x-2.2.1-universal.jar                  | None                                     |
	| LCHIJA | mca                 | 1.12.2-5.3.1           | MCA-1.12.x-5.3.1-universal.jar                        | None                                     |
	| LCHIJA | moreplayermodels    | 1.12.2                 | MorePlayerModels_1.12.2(18jan18).jar                  | None                                     |
	| LCHIJA | travellersbackpack  | 1.0.19.19              | TravellersBackpack-1.12.2-1.0.19.19.jar               | None                                     |
	| LCHIJA | twilightforest      | 3.8.689                | twilightforest-1.12.2-3.8.689-universal.jar           | None                                     |
	| LCHIJA | veinminer           | 0.38.2                 | VeinMiner-1.12-0.38.2.647+b31535a.jar                 | None                                     |
	| LCHIJA | veinminermodsupport | 0.38.2                 | VeinMiner-1.12-0.38.2.647+b31535a.jar                 | None                                     |
	| LCHIJA | waystones           | 4.0.72                 | Waystones_1.12.2-4.0.72.jar                           | None                                     |
	| LCHIJA | wings               | 1.1.5                  | wings-1.1.5-1.12.2.jar                                | None                                     |
	| LCHIJA | bauble_wings        | 1.0.0                  | wings-1.1.5-1.12.2.jar                                | None                                     |
	| LCHIJA | drplibrary          | 1.12.2-0.1.3-SNAPSHOT  | drplibrary-1.12.2-0.1.3-SNAPSHOT-20190129.034240.jar  | 893c317856cf6819b3a8381c5664e4b06df7d1cc |
	| LCHIJA | drpcmmaarg          | 1.12.2-0.10.0-SNAPSHOT | drpcmmaarg-1.12.2-0.10.0-SNAPSHOT-20181116.074036.jar | 893c317856cf6819b3a8381c5664e4b06df7d1cc |
	| LCHIJA | drpcmguis           | 1.12.2-0.0.2-SNAPSHOT  | drpcmguis-1.12.2-0.0.1-SNAPSHOT-20181125.120253.jar   | 893c317856cf6819b3a8381c5664e4b06df7d1cc |
	| LCHIJA | drpcmlocks          | 1.12.2-1.0.1           | drpcmlocks-1.12.2-1.0.0-SNAPSHOT-20181126.111203.jar  | 893c317856cf6819b3a8381c5664e4b06df7d1cc |
	| LCHIJA | drpcore             | 1.12.2-0.4.7           | drpcore-1.12.2-0.4.7.jar                              | 893c317856cf6819b3a8381c5664e4b06df7d1cc |
	| LCHIJA | drpmedieval         | 1.12.2-0.3.5           | drpmedieval-1.12.2-0.3.5.jar                          | None                                     |
	| LCHIJA | drpcmblueprints     | 1.12.2-1.2.3           | drpcmblueprints-1.12.2-1.2.3.jar                      | 893c317856cf6819b3a8381c5664e4b06df7d1cc |
	| UD     | mobends_wings       | 1.0.0                  | wings-1.1.5-1.12.2.jar                                | None                                     |

	Loaded coremods (and transformers): 
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
wings (wings-1.1.5-1.12.2.jar)
  me.paulf.wings.server.asm.WingsRuntimePatcher
  me.paulf.wings.server.asm.mobends.WingsMoBendsRuntimePatcher
MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
  
	Profiler Position: N/A (disabled)
	Player Count: 2 / 50; [EntityPlayerMP['Vahlmira'/4701, l='Please Work', x=-501.71, y=63.00, z=2411.82], EntityPlayerMP['CupOfDrama'/6466, l='Please Work', x=-1152.51, y=66.00, z=-1751.78]]
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by MoriyaShiine** [comment]
this was fixed a while ago

**Comment by Vahlmira** [comment]
That doesn't help me.... It still crashes the server when we try and craft it. Bewitchment is up to its latest date and I don't know and can't tell if there's something interfering with it. ???????

**Comment by MoriyaShiine** [comment]
It's not up to date, you're using 0.20.
