### ISSUE TITLE
[BUG] Blue Ink Cap not spreading

### ISSUE THREAD

**Issue by Shazuli** [Um-Mitternacht/Bewitchment#691]
### Expected Behavior
The Blue Ink Cap whose purpose is a replacement for blue dye doesn't spread, at all. I asked around on the Discord where they explained it spreads very slowly. But from a little testing using a tickrate mod it appears like it never spreads no matter the light level.
<details>
  <summary>They can be used as a blue dye, but they require a blue dye to craft it, making it completely useless.</summary>

![useless2 0](https://user-images.githubusercontent.com/9884180/103459194-a69aab80-4d0d-11eb-9475-d7c2f7bbf87b.jpg)
</details>

### Actual Behavior
They should spread just like regular vanilla mushrooms, or perhaps a functionality with Bonemeal would encourage them to spread.

### Steps to Reproduce
1. Place it down on grass.
2. Wait for heatdeath of the Universe.
3. ???

### Version of Minecraft, Bewitchment, Forge, Patchouli, and Baubles used
Mod | Version
------ | -------
Minecraft | 1.12.2
Forge | 14.23.5.2854
Bewitchment | 1.12.2-0.0.22.49
Baubles | 1.12-1.5.2
Patchouli | 1.0-20
[Tickrate Changer](https://www.curseforge.com/minecraft/mc-mods/tickratechanger) | 1.0.14

#### Screenshot of Blue Ink Cap and Brown Mushroom placed at the same time post time warp showing BIC inability to spread
![2021-01-02_15 29 09](https://user-images.githubusercontent.com/9884180/103459492-1873f480-4d10-11eb-81ed-a10dd9ba436f.png)
#### Another Blue Ink Cap placed at the same time as the other two but in sunlight
![2021-01-02_15 29 17](https://user-images.githubusercontent.com/9884180/103459520-55d88200-4d10-11eb-8602-407326394512.png)

### Additional Info
I did use the vanilla `randomTickSpeed` gamerule too with same result. A tickrate mod would make it more fair but I thought it would be good to throw that info in too to eliminate another mod influencing the result.

**Comment by Sunconure11** [comment]
I need to tweak this, then. The recipes for this is dumb. I can also probably fix the spread, too.

**Comment by Sunconure11** [comment]
Got them spreading again. But nothing with bonemeal yet.

**Comment by Sunconure11** [comment]
I think their spreading should make up for a lack of bonemealing. I've redone how they work and now all magical plants spread. Vanilla's logic works better than whatever we had previously.

**Comment by Shazuli** [comment]
Downloaded first 52 and then 53, but I don't see any plants spreading, and the recipes for some of the plants appear inconsistent. Some of them return the empty jar while other recipes don't:

![plants](https://user-images.githubusercontent.com/9884180/103462038-cbe5e480-4d22-11eb-89a4-167dabb26348.gif)

**Comment by Sunconure11** [comment]
Which recipes are not returning jars?

**Comment by Shazuli** [comment]
The ones in the Gif. Frost Flower, Siphoning Flowers and Blue Ink Cap.

**Comment by Sunconure11** [comment]
Fixed. About to push out another build.

**Comment by Shazuli** [comment]
Very nice. But it appears like the Blue Ink Caps still doesn't spread. I've sped up the world 50x for ~5 min and it still hasn't spread.

**Comment by Sunconure11** [comment]
Okay, that's weird. I sped it up and they spread fine.

**Comment by Sunconure11** [comment]
I had sped it up on my end to something ridiculous for testing purposes. Try higher values, perhaps?

**Comment by Shazuli** [comment]
Doesn't seem to do anything. Placed down regular mushrooms and they started to spread like normal.

![2021-01-02_18 26 49](https://user-images.githubusercontent.com/9884180/103462820-29c8fb00-4d28-11eb-8393-61b2144a1d61.png)

**Comment by Sunconure11** [comment]
I think I see the issue.

**Comment by Sunconure11** [comment]
Should be fixed.

**Comment by Shazuli** [comment]
Yup, seems to be working now:

![2021-01-02_19 07 38](https://user-images.githubusercontent.com/9884180/103463600-dbb6f600-4d2d-11eb-953c-7651b10222e6.png)
